import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Header from '../components/Header';
import Login from '../components/Login';
import CreateNewDoc from '../components/CreateNewDoc';

import Button from '@mui/material/Button';
import IconButton from '@mui/material/IconButton';
import MoreVertIcon from '@mui/icons-material/MoreVert';
import FolderOpenOutlinedIcon from '@mui/icons-material/FolderOpenOutlined';
import ArticleIcon from "@mui/icons-material/Article";


import { getSession, useSession } from "next-auth/react";
import { collection, getDocs, query } from "firebase/firestore";
import { db } from "../firebase";
import { useEffect, useState } from "react";
import { useRouter } from 'next/router';

const style = {
  position: 'absolute',
  top: '50%',
  left: '50%',
  transform: 'translate(-50%, -50%)',
  width: 400,
  bgcolor: 'background.paper',
  boxShadow: 24,
  p: 3,
};

export default function Home() {


  const { data: session } = useSession();
  const [documentData, setDocumentData] = useState([]);
  const router = useRouter();

  if (!session) return <Login />

  useEffect(() => {
    const getData = async () => {
      const q = query(collection(db, "userDocs", session.user.email, "docs"));
      const snapshot = await getDocs(q);
      const data = snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id }));
      setDocumentData(data);
      
    };
    getData();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header session={session} />

      <CreateNewDoc session={session} />


      <section className='bg-white px-20 md:px-0'>
        <div className='max-w-3xl mx-auto py-5 text-sm text-gray-700'>
          <div className='flex items-center justify-between pb-5'>
            <h2 className='font-semibold flex-grow'>My Documents</h2>
            <p className='mr-12'>Date Created</p>
            <FolderOpenOutlinedIcon size="3xl">folder</FolderOpenOutlinedIcon>
          </div>
          {documentData?.map((doc) => {
            return (
              <div key={doc.id} onClick={() => router.push(`/doc/${doc.id}`)} className="flex items-center p-2 rounded-md hover:bg-gray-100 text-gray-700 text-sm cursor-pointer">
                <ArticleIcon className="text-blue-500" />
                <p className="flex-grow pl-5 w-10 pr-10 truncate">
                  {doc.filename}
                </p>
                <p className="pr-5 text-sm">
                  {doc.timestamp?.toDate().toLocaleDateString()}
                </p>
                <IconButton>
                  <MoreVertIcon />
                </IconButton>
              </div>
            );
          })}
        </div>
      </section>

      {/* <h1 className="text-3xl font-bold underline">
        Hello world!
      </h1>
      <Button variant="contained" className=''>Contained</Button> */}
    </div>
  )
}

export async function getServerSideProps(context) {

  const session = await getSession(context);

  return {

    props: {
      session,
    }

  }

}